name: Build Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    # we need to fetch the whole history to be able to get the latest tag
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login to the registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username "${{ github.actor }}" --password-stdin $(make get-registry)

    - name: Build & Release base containers
      run: make release

    - name: Build & Release example containers
      run: make release-examples
