name: Build Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to the registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username "${{ github.actor }}" --password-stdin $(make get-registry)

    - name: Build & Release base containers
      run: make release

    - name: Build & Release example containers
      run: make release-examples
