FROM docker.io/library/archlinux
# image-name: ostreefy/base/archlinux

# Clock
ARG SYSTEM_OPT_TIMEZONE=Etc/UTC
RUN ln -sf /usr/share/zoneinfo/${SYSTEM_OPT_TIMEZONE} /etc/localtime

# Remove container specific storage optimization in Pacman
RUN sed -i -e "s|^NoExtract.*||g" /etc/pacman.conf && \
    pacman --noconfirm -Syu

# Keymap hook
ARG SYSTEM_OPT_KEYMAP=us
RUN echo "KEYMAP=${SYSTEM_OPT_KEYMAP}" | tee /etc/vconsole.conf

# Language
RUN echo "LANG=en_US.UTF-8" | tee /etc/locale.conf && \
    echo "en_US.UTF-8 UTF-8" | tee /etc/locale.gen && \
    locale-gen

# Networking
RUN pacman --noconfirm -S networkmanager && \
    systemctl enable NetworkManager.service && \
    systemctl mask systemd-networkd-wait-online.service

## |
## | OSTREE INSTALLATION
## |

# Prepare OSTree integration (https://wiki.archlinux.org/title/Mkinitcpio#Common_hooks)
RUN mkdir -p /etc/mkinitcpio.conf.d && \
    echo "HOOKS=(base systemd ostree autodetect modconf kms keyboard sd-vconsole block filesystems fsck)" >> /etc/mkinitcpio.conf.d/ostree.conf

# Install kernel, firmware, microcode, filesystem tools, bootloader, depndencies and run hooks once:
RUN pacman --noconfirm -S \
    linux \
    linux-headers \
    linux-firmware \
    amd-ucode \
    \
    dosfstools \
    xfsprogs \
    \
    grub \
    mkinitcpio \
    \
    podman \
    ostree \
    which

# OSTree: Prepare microcode and initramfs
RUN moduledir=$(find /usr/lib/modules -mindepth 1 -maxdepth 1 -type d) && \
    cat /boot/*-ucode.img \
        /boot/initramfs-linux-fallback.img \
        > ${moduledir}/initramfs.img

# OSTree: Bootloader integration
RUN curl https://raw.githubusercontent.com/ostreedev/ostree/v2023.6/src/boot/grub2/grub2-15_ostree -o /etc/grub.d/15_ostree && \
    chmod +x /etc/grub.d/15_ostree

# Podman: native Overlay Diff for optimal Podman performance
RUN echo "options overlay metacopy=off redirect_dir=off" > /etc/modprobe.d/disable-overlay-redirect-dir.conf

# Mount disk locations
ARG OSTREE_SYS_BOOT_LABEL=SYS_BOOT
ARG OSTREE_SYS_ROOT_LABEL=SYS_ROOT
ARG OSTREE_SYS_HOME_LABEL=SYS_HOME
RUN echo "LABEL=${OSTREE_SYS_ROOT_LABEL} /         xfs  rw,relatime                                                                                           0 1" >> /etc/fstab && \
    echo "LABEL=${OSTREE_SYS_HOME_LABEL} /var/home xfs  rw,relatime                                                                                           0 2" >> /etc/fstab && \
    echo "LABEL=${OSTREE_SYS_BOOT_LABEL} /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 2" >> /etc/fstab

# Root password (todo move to secret)
RUN echo "root:ostree" | chpasswd

COPY post.d/* /usr/share/ostreefy/post.d/
